{
 "title": "Restic Controller",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Repositories integrity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "restic_repo_integrity_status", "legendFormat": "{{ repository }}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "restic_repo_integrity_status_latest_seconds * 1000",
     "legendFormat": "{{ repository }}"
    }
   ]
  },
  {
   "title": "Total number of snapshots per repository",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "snapshot count " }
   ],
   "targets": [
    {
     "expr": "sum by (repository) (restic_repo_snapshots_total)",
     "legendFormat": "{{ repository }}"
    }
   ]
  },
  {
   "title": "Total number of snapshots per group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "snapshot count " }
   ],
   "targets": [
    {
     "expr": "sum by (repository, host, paths) (restic_group_snapshots_total)"
    }
   ]
  },
  {
   "title": "Latest snapshots",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "restic_group_snapshot_latest_seconds * 1000"
    },
    {
     "expr": "time() - (restic_group_snapshot_latest_seconds)"
    }
   ]
  },
  {
   "title": "Retention policy last applies",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "restic_repo_retention_forget_latest_seconds * 1000"
    },
    {
     "expr": "time() - (restic_repo_retention_forget_latest_seconds)"
    }
   ]
  }
 ]
}